apiVersion: networking.istio.io/v1beta1
kind: DestinationRule
metadata:
  name: aichat-destination-rule
  namespace: aichat
spec:
  host: backend-service.aichat.svc.cluster.local
  trafficPolicy:
    tls:
      mode: ISTIO_MUTUAL
