services:
  frontend:
    image: nginx:alpine
    ports:
      - "80:80"
    volumes:
      - ./src/frontend:/usr/share/nginx/html
    depends_on:
      - backend

  backend:
    build: ./src/backend
    ports:
      - "8000:8000"
    environment:
      - CHROMA_HOST=vectordb
      - CHROMA_PORT=8000
    depends_on:
      - vectordb
    volumes:
      - ./docs:/app/docs                              # docsをマウント
      - ./README.md:/app/README.md                    # README.mdをマウント
      - ./src/backend/templates:/app/templates        # templatesをマウント

  vectordb:
    image: chromadb/chroma:latest
    ports:
      - "8001:8000"
    volumes:
      - chroma-data:/chroma/chroma
    environment:
      - IS_PERSISTENT=TRUE

volumes:
  chroma-data:
