server {
    listen 80;

    root /usr/share/nginx/html;

    # /api/specs → backend:8000/api/specs
    location /api/specs {
        proxy_pass http://backend:8000/api/specs;
    }

    location /api/docs/ {
        proxy_pass http://backend:8000/api/docs/;
    }

    location /api/root_meta/ {
        proxy_pass http://backend:8000/api/root_meta/;
    }

    # その他の /api/ は backend に流す
    location /api/ {
        proxy_pass http://backend:8000/;
    }
    location = /favicon.ico {
        return 204;
    }

    location /favicon.ico {
        alias /usr/share/nginx/html/favicon.ico;
    }
}
