apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

# 1. 大元（base）の設計図を読み込む
resources:
  - ../../base

# 2. Minikube環境だけで適用したい「上書き設定」
# 例: ポッド数を1つにする、ローカル用の環境変数を差し込むなど
patches:
  - target:
      kind: Deployment
      name: backend
    patch: |-
      - op: replace
        path: /spec/replicas
        value: 1
